# Generated by Django 2.1 on 2018-08-11 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
